create table mirante.account (
  id int primary key generated by default as identity,

  name text not null,
  email text not null,
  registration text not null,
  verified boolean not null default false,

  role name not null default current_user,

  creation_date timestamptz not null default now(),
  active boolean not null default true,
  locked boolean not null default false,
  expired boolean not null default false
);
