create table mirante.course (
  id int primary key generated by default as identity,

  name text not null,
  expiry_date timestamptz,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  active boolean not null default true,
);
