create table mirante.exercise_set (
  id int primary key generated by default as identity,

  name text not null,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  enabled boolean not null default true
);
