create table mirante.exercise (
  id int primary key generated by default as identity,

  instruction text not null,

  set int references exercise_set(id) not null,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  enabled boolean not null default true
);
