create table mirante.option (
  id int primary key generated by default as identity,

  content text not null,
  correct boolean not null default false,
  place int,

  exercise int references exercise(id) not null,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  enabled boolean not null default true
);

grant select, insert, update, delete on mirante.option to base_user;

alter table mirante.option enable row level security;

create policy option_policy_select on mirante.option for select
using (creation_user = current_user);

create policy option_policy_update on mirante.option for update
using (creation_user = current_user);

create policy option_policy_delete on mirante.option for delete
using (creation_user = current_user);

create policy option_policy_insert on mirante.option for insert
to base_user with check (true);
