create table mirante.option (
  id int primary key generated by default as identity,

  content text not null,
  correct boolean not null default false,
  place int,

  exercise int references exercise(id) not null,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  enabled boolean not null default true
);
