create table mirante.response (
  id int primary key generated by default as identity,

  option int references option(id),
  place int,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user,
  enabled boolean not null default true
);
