create table mirante.metric (
  id int primary key generated by default as identity,

  period_from timestamptz not null default now(),
  period_to timestamptz not null default now(),

  accuracy numeric,
  retention numeric,
  assiduity numeric,

  creation_date timestamptz not null default now(),
  creation_user name not null default current_user
);

grant select, insert, update, delete on mirante.metric to base_user;

alter table mirante.metric enable row level security;

create policy metric_policy_select on mirante.metric for select
using (creation_user = current_user);

create policy metric_policy_update on mirante.metric for update
using (creation_user = current_user);

create policy metric_policy_delete on mirante.metric for delete
using (creation_user = current_user);

create policy metric_policy_insert on mirante.metric for insert
to base_user with check (true);
