create table mirante.course (
  id int primary key generated by default as identity,
  active boolean not null default false,
  name text not null,
  creation_date timestamptz not null,
  start_date timestamptz not null,
  end_date timestamptz
);
