create table mirante.account (
  id int primary key generated by default as identity,
  name text not null,
  email text not null,
  registration text not null,
  registration_date timestamptz not null,
  active boolean not null default true,
  verified boolean not null default false,
  locked boolean not null default false,
  expired boolean not null default false
);
