create table mirante.response (
  id int primary key generated by default as identity,
  date timestamptz not null,
  author int references account(id),
  option int references option(id),
  place int,
  expiry_date timestamptz,
  active boolean not null default true,
  locked boolean not null default false,
  expired boolean not null default false
);
