services:
  db:
    container_name: mirante-db
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/mirante/data:/var/lib/postgresql/data
      - "./initdb:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    container_name: mirante-api
    restart: always
    image: postgrest/postgrest:v12.2.3
    ports:
      - "3031:3000"
    environment:
      - PGRST_JWT_SECRET=${MIRANTE_JWT_SECRET}
      - PGRST_APP_SETTINGS_JWT_SECRET=${MIRANTE_JWT_SECRET}
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMAS=mirante
      - PGRST_DB_ANON_ROLE=anonymous
    depends_on:
      db:
        condition: service_healthy
        restart: true
