create schema mirante;

create table mirante.version (
  id int primary key generated by default as identity,
  deprecated boolean not null default false,
  tag text not null,
  date timestamptz
);

insert into mirante.version (tag) values
  ('v0.3.0'), ('v0.4.0');

create role anonymous nologin;
grant usage on schema mirante to anonymous;
grant select on mirante.version to anonymous;

-- <secret> must be edited and safely stored before execution
create role authenticator noinherit login password '<secret>';
